### ISSUE TITLE
de-anonymizing conflicts of interest

### ISSUE THREAD

**Issue by richsalz** [ietf-llc/policies-consultation#11]
This is not a suggested wording for the policy, but something that the LLC needs to keep in mind. Since the population of covered individuals is so small, the Board needs to think carefully about how it presents its "summary data" so as to not expose individuals. In particular, the "more frequently when and if updates to individual disclosures" would expose "timing attacks" as it were. :)

Or is the goal of the transparency section that individual data is posted?  Or individual data is posted but the name is witheld? Or something else?  That should be cleared up.

**Comment by jlivingood** [comment]
Good advice as we ponder how to do disclosures. I think the current plan is to have the disclosures available on a per-person basis, per "The IETF LLC Board will also publicly publish a summary of disclosures and resolutions, both as summary statistics (e.g. total number of disclosure forms received) as well as individual-level disclosures."

But some of the specific details in (named) individual-level disclosures may be redacted.

Anyway - good advice for us to keep in mind when we do this.
