### ISSUE TITLE
retention matrix put into a "schedule A"

### ISSUE THREAD

**Issue by richsalz** [ietf-llc/policies-consultation#12]
In my experience, things like the retention matrix can be very usefully put into a Schedule A, and the retention policy says something like "Records are kept according to the lifetimes maintained in Schedule A, which is incorporated into this policy by reference" or similar. Then they can be updated separately, it becomes clear when something changes, and so on.

**Comment by jlivingood** [comment]
Change made in https://github.com/ietf-llc/policies-consultation/blob/master/Records-Retention-00.md
