### ISSUE TITLE
Ambiguity of covered/non-covered persons

### ISSUE THREAD

**Issue by richsalz** [ietf-llc/policies-consultation#13]
The Covered Individual document lists people who are covered by LLC policies. The second paragraph lists people who are not. I assume the intent is that the two paragraphs together cover everyone, but they really don't. Is some random individual employee of Cisco covered? The US President?  Etc. etc.

I think the second paragraph should start with something like "People not identified in the first paragraph are not covered individuals. This includes ..."

**Comment by jlivingood** [comment]
ok - will make a change to address that

**Comment by jlivingood** [comment]
Note that this change is out for review w/counsel.
https://github.com/ietf-llc/policies-consultation/pull/20/commits/d132cdaec15d0cfff4625b257bd1a6ae88fa1a49
