### ISSUE TITLE
Coi "confidential information"

### ISSUE THREAD

**Issue by sftcd** [ietf-llc/policies-consultation#14]
I think the "confidential information" mentioned in the draft CoI policy that is not provided in the public disclosures is unclear. I assume what's meant is the e.g. if someone discloses that they have a project/contract with some entity for $X, that the X would be omitted but the name of the entity would be made public. I think there ought be few to zero cases where the names of such entities are not made public and maybe that ought be clarified in the policy, with some indication of what kind(s) of information are ok to not disclose. (The default for all LLC things to be as open as possible as I think the iasa2 wg agreed.)

**Comment by coopdanger** [comment]
I think "confidential information" needs to include any information that the Covered Individual is obligated to keep confidential. For example, if I'm a contractor and I've signed an NDA that requires me to keep the existence of my contract confidential, that would comprise confidential information.

**Comment by sftcd** [comment]
yep, that's the tricky one - in such a case, if an LLC board member declares, then recuses from some vote as is proper, I've no idea how that could be explained to the community, but even if nothing can be done about that, I think some more explanation on this would be useful, as well as making it clear (if it's not already) that that's a) an exception and b) not desirable.

**Comment by bobhinden** [comment]
Alissa,

> On Jun 25, 2019, at 9:21 AM, Alissa Cooper <notifications@github.com> wrote:
> 
> I think "confidential information" needs to include any information that the Covered Individual is obligated to keep confidential. For example, if I'm a contractor and I've signed an NDA that requires me to keep the existence of my contract confidential, that would comprise confidential information.
> 

I thought this was discussed earlier on the list.  My take was that if a board member has conflicts that can’t be disclosed, then they shouldn’t be a board member.

Bob

**Comment by coopdanger** [comment]
It was discussed but I don't think it was resolved in such a way that consensus about that was documented anywhere.

**Comment by jlivingood** [comment]
@bobhinden I suspect that un-disclosable conflicts are going to be a problem, but seems unclear whether it will be an actual one in practice. Something un-disclosable will raise a lot of questions and it would seem there may well be many other non-conflicted candidates for these positions. Perhaps one way to address this may be during the NomCom process where a CoI could be completed & sent to the Board and the Board could advise whether there were any issues. But I am not clear how real this issue is or whether it is just theoretical. Perhaps judge this based on the initial CoI filings from us, which I expect fairly soon.

**Comment by jlivingood** [comment]
@sftcd Some of the info probably should be redacted if it is totally unrelated to the IETF. For example, will it matter to the IETF that my father-in-law is the co-owner of an automobile dealership, that my sister is sole owner of a photography business, etc.? Excessive disclosure may well be a barrier to service for very senior personnel in the future. We should IMO be focused on maximizing transparency on those potential CoIs that are directly relevant to the work of the IETF. It seems that this will necessarily require the Board to exercise their judgement. I hope the IETF community can similarly wait to see the initial CoIs and then assess thoughts in this area on whether we have struck the right balance.

**Comment by jlivingood** [comment]
No further action needed - but Board should keep this discussion in mind (will share via Slack).

**Comment by sftcd** [comment]
Again, I'd need to go back and reinstate the context but ISTM
that nothing confidential ought be relevant to the IETF. If you
can find a way to say that, that'd be fine by me but I remain
allergic to the idea that some relevant CoI is kept secret as
that seems to me to entirely defeat the transparency aspect
of the CoI declarations (and would be generally whiffy).

Cheers,
S.
