### ISSUE TITLE
CoI "gifts/hospitality"

### ISSUE THREAD

**Issue by sftcd** [ietf-llc/policies-consultation#15]
Various other CoI policies require people to disclose gifts or hospitality received that is worth more than some value. That's not included here, should it be?

**Comment by jlivingood** [comment]
Not sure. We already discuss that in the Code of Conduct, Section 9, rather extensively at https://github.com/ietf-llc/policies-consultation/blob/master/Code-of-Conduct-00.md 

@sftcd Thoughts?

**Comment by sftcd** [comment]
On 22/10/2019 20:40, Jason Livingood wrote:
> Not sure. We already discuss that in the Code of Conduct, Section 9,
> rather extensively at
> https://github.com/ietf-llc/policies-consultation/blob/master/Code-of-Conduct-00.md
>  
> @sftcd Thoughts?

TBH, I forget my comment but do recall finding that later:-)

I think (but would need to check) the context here was me wanting
to include some such in the IAB CoI policy. That said, I think the
specifics of gifts maybe ought differ for LLC board and IAB so it
is likely ok as-is for the LLC policy. (For the IAB, I think a
simple register of gifts >€N is probably ok as IAB folk don't
make direct €€€ decisions.)

Cheers,
S.

**Comment by jlivingood** [comment]
Thanks!
