### ISSUE TITLE
"much" is public vs. open by default

### ISSUE THREAD

**Issue by sftcd** [ietf-llc/policies-consultation#16]
The code of conduct says "While much of the work of the IETF LLC is public information..."
That seems to me less than what the iasa2 wg agreed which was that the LLC would be open by default with things being confidential as the exception where necessary. It'd be a fine thing to say that explicitly here too.

**Comment by jlivingood** [comment]
Ack. Opened a pull request with this change for Board discussion. 

https://github.com/ietf-llc/policies-consultation/pull/21/commits/899f29fa459581fb4546efd8b5fc45a31403f071
