### ISSUE TITLE
ISOC-related conflict

### ISSUE THREAD

**Issue by coopdanger** [ietf-llc/policies-consultation#18]
Does this policy need to say anything specific about conflicts related to ISOC trustees, employees, or contractors, given the legal relationship between IETF LLC and ISOC?

**Comment by jlivingood** [comment]
Would that be covered in part III of the disclosure form at https://github.com/ietf-llc/policies-consultation/blob/master/Conflict-of-Interest-00.md? 

Perhaps we would need to add some text such as this parenthetical -

> Other activities I participate in that may be in a similar area of activity as the IETF Administration LLC, or other potential conflicts of interests with my IETF Administration LLC responsibilities (incl. those related to the Internet Society, Public Interest Registry, or other IETF and ISOC-related entities):

**Comment by jlivingood** [comment]
Per counsel: Thanks for bringing this to our attention. We agree that the disclosure should cover the concern raised, and that it should be fairly obvious to Covered Individuals that any relationships with ISOC or PIR would be subject to the disclosure requirement. Our (minor) hesitation with the addition of the parenthetical is the potential implication that the list is illustrative of all the types of organizations that would be subject to the disclosure requirement - as opposed to the broader scope description that precedes the parenthetical. However, if the board feels like the addition is helpful context, we don't see an issue with it per se.  

JL: I recommend we proceed w/o the parenthetical. If anyone feels strongly pls raise it on the 31-Oct-2019 board call.
