### ISSUE TITLE
Family members

### ISSUE THREAD

**Issue by coopdanger** [ietf-llc/policies-consultation#19]
Is the language about family members and related parties clear enough about which kinds of family members this applies to (e.g., second cousins, etc.)?

**Comment by jlivingood** [comment]
Good point. Maybe we need to say "direct family members (e.g. spouse/partner, children, parents, siblings)"?

I will ask counsel to weigh in here on the best practice.

**Comment by jlivingood** [comment]
From counsel:

It's a good point. We propose to add the following to the CoI. 

For purposes of this policy and related disclosures, "family" means a spouse, domestic partner, child, sibling, parent, stepchild, stepparent, and mother-, father-, son-, daughter-, brother-, or sister-in-law, and any other person living in the same household, except tenants and household employees."

I will make that change.
