### ISSUE TITLE
Whistleblower policy is unclear on who may be considered a whistleblower

### ISSUE THREAD

**Issue by hardie** [ietf-llc/policies-consultation#2]
The policy inherits the definition of "covered individual", which is clear on who is and is not covered.  The policy imposes certain responsibilities on covered individuals, but it is a bit ambiguos whether non-covered individuals who act as whistle blowers are covered by the anti-retaliation aspects of the policy. 

There seem to be two ways to adjust this.  One is to adjust "Reporting responsibility" to note that non-covered individuals may act as whistle blowers and confirm the rest of the policies against retaliation apply.  Alternatively, this could be specified in the reporting procedure.

**Comment by jlivingood** [comment]
Ack. Will send this to counsel for their assessment.

**Comment by jlivingood** [comment]
Comment from counsel for discussion with the Board:

This particular issue was actually considered in the drafting of the policy. The current draft policy uses the term “Covered Individual” sparingly vs. the more general term “complainant” to draw the distinction between the aspects of the policy that apply only to Covered Individuals vs. those that apply to complainants as a whole. There is also explicit language stating that “anyone may submit reports”. However, if the community and board continue to believe there is a reason for concern based on the current draft, we could implement the tweaks below. 

Tweak 1: Intro to policy: 
Current draft: “It is the policy of IETF LLC not to retaliate against good faith reports of inappropriate, unethical or illegal conduct. Anyone may submit such reports.”
Potential tweak: “Anyone (not only Covered Individuals) may submit good faith reports of inappropriate, unethical or illegal conduct. It is the policy of IETF LLC not to retaliate against any such reports, whether or not the complainant is a Covered Individual.”

Tweak 2: Report Processing: 
“No complainant (whether or not a Covered Individual) who has made a complaint in good faith shall suffer harassment or retaliation for such complaint by a Covered Individual. Any Covered Individual who retaliates against a complainant acting in good faith will be subject to appropriate discipline, which may include termination of their relationship with IETF LLC. A Covered Individual who makes a report in bad faith will be subject to appropriate discipline, including termination of their relationship with IETF LLC.”

**Comment by hardie** [comment]
Potential tweak one looks easier to me for the community to grok, if the board has no other preference between the two.

**Comment by jlivingood** [comment]
Noting that the last part of tweak 2 read “which may include termination” should likely change to “including termination”

**Comment by jlivingood** [comment]
New tweak 2 reads as follows and seems easiest & looks good to Ted as well

Tweak 2: Report Processing:
“No complainant (whether or not a Covered Individual) who has made a complaint in good faith shall suffer harassment or retaliation for such complaint by a Covered Individual. Any Covered Individual who retaliates against a complainant acting in good faith will be subject to appropriate discipline, including termination. A Covered Individual who makes a report in bad faith will be subject to appropriate discipline, including termination of their relationship with IETF LLC.”

**Comment by jlivingood** [comment]
New PR created at https://github.com/ietf-llc/policies-consultation/pull/29
And merging in a sec
