### ISSUE TITLE
RSOC members

### ISSUE THREAD

**Issue by coopdanger** [ietf-llc/policies-consultation#28]
The Covered Individuals description says that IAB program members are not Covered Individuals. RSOC is an IAB program, so from this I would assume RSOC members are not Covered Individuals. However, RSOC members are involved in the selection of IETF LLC contractors, so it seems like at a minimum the Conflict of Interest policy should apply to them.

**Comment by jlivingood** [comment]
Pull request created. Bouncing to counsel via email.
https://github.com/ietf-llc/policies-consultation/pull/30/commits/c769ed54e5a8f1ede96c7dfd840791cc9da8df96
