### ISSUE TITLE
Covered Individuals needs rationale

### ISSUE THREAD

**Issue by richsalz** [ietf-llc/policies-consultation#7]
Why is it necessary to defined Covered Individuals?  That explanation should be in the policy document that defines them I think.

**Comment by jlivingood** [comment]
We have to define Covered Individuals someplace -- not sure what the issue is. In any case, if you have feedback on the text of Covered Individuals that is fine.

**Comment by richsalz** [comment]
I get that you have to defined it.  I'm saying that you should have the reason. I don't think I can offer wording, since I'm not sure who/what/why is covered.  Maybe something like "IETF LLC policies apply to certain classes of individuals, as identified below" ?

**Comment by jlivingood** [comment]
Yes, we will be doing that.
